import type { TInitialItemGroups, TInitialItemImages, TinitialItems } from '../../types';

const intialItemGroups: TInitialItemGroups = {
  'macbook-pro-14-m3-pro': {
    groupName: 'macbook-pro-14-m3-pro',
    optionKeys: ['COLOR', 'TYPE'],
  },
  'macbook-air-13-m3': {
    groupName: 'macbook-air-13-m3',
    optionKeys: ['COLOR', 'TYPE'],
  },
};

const initialItemImages: TInitialItemImages = {
  'macbook-pro-14-m3-pro': {
    'silver': [
      'items/notebooks/macbook-pro-14-m3-pro/macbook-pro-14-m3-pro-silver.webp',
      'items/notebooks/macbook-pro-14-m3-pro/macbook-pro-14-m3-pro-silver-2.webp',
      'items/notebooks/macbook-pro-14-m3-pro/macbook-pro-14-m3-pro-silver-3.webp',
      'items/notebooks/macbook-pro-14-m3-pro/macbook-pro-14-m3-pro-silver-4.webp',
      'items/notebooks/macbook-pro-14-m3-pro/macbook-pro-14-m3-pro-silver-5.webp',
    ],
    'space-black': [
      'items/notebooks/macbook-pro-14-m3-pro/macbook-pro-14-m3-pro-space-black.webp',
      'items/notebooks/macbook-pro-14-m3-pro/macbook-pro-14-m3-pro-space-black-2.webp',
      'items/notebooks/macbook-pro-14-m3-pro/macbook-pro-14-m3-pro-space-black-3.webp',
      'items/notebooks/macbook-pro-14-m3-pro/macbook-pro-14-m3-pro-space-black-4.webp',
    ]
  },
  'macbook-air-13-m3': {
    'midnight': [
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-midnight.webp',
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-midnight-2.webp',
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-midnight-3.webp',
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-midnight-4.webp',
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-midnight-5.webp',
    ],
    'silver': [
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-silver.webp',
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-silver-2.webp',
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-silver-3.webp',
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-silver-4.webp',
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-silver-5.webp',
    ],
    'space-gray': [
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-space-gray.webp',
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-space-gray-2.webp',
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-space-gray-3.webp',
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-space-gray-4.webp',
      'items/notebooks/macbook-air-13-m3/macbook-air-13-m3-space-gray-5.webp',
    ],
  }
};

export const initialItems: TinitialItems[] = [
  // air, midnight
  {
    name: 'MacBook Air 13 Retina, Midnight, 256GB, 8 CPU / 10 GPU, 8GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1199,
    priceDiscount: 1199,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Midnight', 'TYPE': '8Gb / 256Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['midnight'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "8Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "256Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Midnight, 512GB, 8 CPU / 10 GPU, 8GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1399,
    priceDiscount: 1399,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Midnight', 'TYPE': '8Gb / 512Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['midnight'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "8Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "512Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Midnight, 256GB, 8 CPU / 10 GPU, 16GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1499,
    priceDiscount: 1499,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Midnight', 'TYPE': '16Gb / 256Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['midnight'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "16Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "256Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Midnight, 512GB, 8 CPU / 10 GPU, 16GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1799,
    priceDiscount: 1799,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Midnight', 'TYPE': '16Gb / 512Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['midnight'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "16Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "512Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Midnight, 1Tb, 8 CPU / 10 GPU, 16GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1999,
    priceDiscount: 1999,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Midnight', 'TYPE': '16Gb / 1Tb' },
    stockQty: 5,
    bestSeller: true,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['midnight'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "16Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "1Tb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Midnight, 512GB, 8 CPU / 10 GPU, 24GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1799,
    priceDiscount: 1799,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Midnight', 'TYPE': '24Gb / 512Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['midnight'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "24Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "512Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Midnight, 1Tb, 8 CPU / 10 GPU, 24GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1999,
    priceDiscount: 1999,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Midnight', 'TYPE': '24Gb / 1Tb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['midnight'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "24Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "1TbGb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  // air, silver
  {
    name: 'MacBook Air 13 Retina, Silver, 256GB, 8 CPU / 10 GPU, 8GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1199,
    priceDiscount: 1199,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Silver', 'TYPE': '8Gb / 256Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['silver'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "8Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "256Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Silver, 512GB, 8 CPU / 10 GPU, 8GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1399,
    priceDiscount: 1399,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Silver', 'TYPE': '8Gb / 512Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['silver'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "8Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "512Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Silver, 256GB, 8 CPU / 10 GPU, 16GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1499,
    priceDiscount: 1499,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Silver', 'TYPE': '16Gb / 256Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['silver'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "16Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "256Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Silver, 512GB, 8 CPU / 10 GPU, 16GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1999,
    priceDiscount: 1999,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Silver', 'TYPE': '16Gb / 512Gb' },
    stockQty: 5,
    bestSeller: true,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['silver'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "16Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "512Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Silver, 1Tb, 8 CPU / 10 GPU, 16GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 2399,
    priceDiscount: 2399,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Silver', 'TYPE': '16Gb / 1Tb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['silver'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "16Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "1Tb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Silver, 512GB, 8 CPU / 10 GPU, 24GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 2499,
    priceDiscount: 2499,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Silver', 'TYPE': '24Gb / 512Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['silver'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "24Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "512Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Silver, 1Tb, 8 CPU / 10 GPU, 24GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 2699,
    priceDiscount: 2699,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Silver', 'TYPE': '24Gb / 1Tb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['silver'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "24Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "1TbGb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  // air, space-gray
  {
    name: 'MacBook Air 13 Retina, Space Gray, 256GB, 8 CPU / 10 GPU, 8GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1199,
    priceDiscount: 1199,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Space Gray', 'TYPE': '8Gb / 256Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['space-gray'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "8Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "256Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Space Gray, 512GB, 8 CPU / 10 GPU, 8GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1399,
    priceDiscount: 1399,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Space Gray', 'TYPE': '8Gb / 512Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['space-gray'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "8Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "512Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Space Gray, 256GB, 8 CPU / 10 GPU, 16GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1499,
    priceDiscount: 1499,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Space Gray', 'TYPE': '16Gb / 256Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['space-gray'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "16Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "256Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Space Gray, 512GB, 8 CPU / 10 GPU, 16GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 1999,
    priceDiscount: 1999,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Space Gray', 'TYPE': '16Gb / 512Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['space-gray'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "16Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "512Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Space Gray, 1Tb, 8 CPU / 10 GPU, 16GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 2399,
    priceDiscount: 2399,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Space Gray', 'TYPE': '16Gb / 1Tb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['space-gray'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "16Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "1Tb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Space Gray, 512GB, 8 CPU / 10 GPU, 24GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 2499,
    priceDiscount: 2499,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Space Gray', 'TYPE': '24Gb / 512Gb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['space-gray'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "24Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "512Gb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  {
    name: 'MacBook Air 13 Retina, Space Gray, 1Tb, 8 CPU / 10 GPU, 24GB RAM with Apple M3 (MXCV3)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 2699,
    priceDiscount: 2699,
    ourItem: true,
    groupKey: intialItemGroups['macbook-air-13-m3'].groupName,
    groupOptions: { 'COLOR': 'Space Gray', 'TYPE': '24Gb / 1Tb' },
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-air-13-m3']['space-gray'],
    spec: {
      "Display": "13.6-inch Liquid Retina display with True Tone²",
      "Processor": "Apple M3 processor 8-core CPU",
      "RAM": "24Gb",
      "Ports": "Two Thunderbolt / USB 4 ports",
      "Camera": "1080p FaceTime HD camera",
      "Storage": "1TbGb",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.24kg",
      "Dimensions": "(HWD)	1.13 x 30.41 x 21.5cm",
      "Battery": "Capacity	56.2Wh",
      "Operating System": "macOS",
    }
  },
  // pro
  {
    name: 'Apple MacBook Pro 14 with Apple M3 Pro, 512GB, 11 CPU / 14 GPU, 18GB RAM, Space Black 2023 (MRX33)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 2499,
    priceDiscount: 2499,
    ourItem: true,
    groupKey: intialItemGroups['macbook-pro-14-m3-pro'].groupName,
    groupOptions: { 'COLOR': 'Space Black', 'TYPE': '18Gb / 512Gb' },
    stockQty: 2,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-pro-14-m3-pro']['space-black'],
    spec: {
      "Display": "14in liquid retina XDR, 3024 x 1964 resolution, 254 pixels per inch",
      "Processor": "Apple M3 Pro processor 11-core CPU",
      "GPU": "14-core GPU",
      "RAM": "18GB",
      "Ports": "HDMI port, 2 x Thunderbolt 4 (charging, display), 3.5mm headphone jack and a MagSafe 3 port",
      "Camera": "1080p HD camera",
      "Storage": "512 Gb SSD",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.55Kg",
      "Dimensions": "(HWD)	1.55 x 31.26 x 22.12 cm",
      "Battery": "Capacity	70Wh lithium-polymer batter, 70Wh power adapter",
      "Operating System": "macOS Sonoma 14.1",
    }
  },
  {
    name: 'Apple MacBook Pro 14 with Apple M3 Pro, 1TbGB, 11 CPU / 14 GPU, 18GB RAM, Space Black 2023 (MRX33)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 2799,
    priceDiscount: 2799,
    ourItem: true,
    groupKey: intialItemGroups['macbook-pro-14-m3-pro'].groupName,
    groupOptions: { 'COLOR': 'Space Black', 'TYPE': '18Gb / 1Tb' },
    stockQty: 2,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-pro-14-m3-pro']['space-black'],
    spec: {
      "Display": "14in liquid retina XDR, 3024 x 1964 resolution, 254 pixels per inch",
      "Processor": "Apple M3 Pro processor 11-core CPU",
      "GPU": "14-core GPU",
      "RAM": "18GB",
      "Ports": "HDMI port, 2 x Thunderbolt 4 (charging, display), 3.5mm headphone jack and a MagSafe 3 port",
      "Camera": "1080p HD camera",
      "Storage": "1Tb SSD",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.55Kg",
      "Dimensions": "(HWD)	1.55 x 31.26 x 22.12 cm",
      "Battery": "Capacity	70Wh lithium-polymer batter, 70Wh power adapter",
      "Operating System": "macOS Sonoma 14.1",
    }
  },
  {
    name: 'Apple MacBook Pro 14 with Apple M3 Pro, 512GB, 11 CPU / 14 GPU, 18GB RAM, Silver 2023 (MRX33)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 2499,
    priceDiscount: 2499,
    ourItem: true,
    groupKey: intialItemGroups['macbook-pro-14-m3-pro'].groupName,
    groupOptions: { 'COLOR': 'Silver', 'TYPE': '18Gb / 512Gb' },
    stockQty: 0,
    bestSeller: true,
    forSale: false,
    itemImages: initialItemImages['macbook-pro-14-m3-pro']['silver'],
    spec: {
      "Display": "14in liquid retina XDR, 3024 x 1964 resolution, 254 pixels per inch",
      "Processor": "Apple M3 Pro processor 11-core CPU",
      "GPU": "14-core GPU",
      "RAM": "18GB",
      "Ports": "HDMI port, 2 x Thunderbolt 4 (charging, display), 3.5mm headphone jack and a MagSafe 3 port",
      "Camera": "1080p HD camera",
      "Storage": "512 Gb SSD",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.55Kg",
      "Dimensions": "(HWD)	1.55 x 31.26 x 22.12 cm",
      "Battery": "Capacity	70Wh lithium-polymer batter, 70Wh power adapter",
      "Operating System": "macOS Sonoma 14.1",
    }
  },
  {
    name: 'Apple MacBook Pro 14 with Apple M3 Pro, 1TbGB, 11 CPU / 14 GPU, 18GB RAM, Silver 2023 (MRX33)',
    url: '',
    brandId: 2,
    categoryId: 2,
    storeId: 1,
    price: 2799,
    priceDiscount: 2799,
    ourItem: true,
    groupKey: intialItemGroups['macbook-pro-14-m3-pro'].groupName,
    groupOptions: { 'COLOR': 'Silver', 'TYPE': '18Gb / 1Tb' },
    stockQty: 0,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['macbook-pro-14-m3-pro']['silver'],
    spec: {
      "Display": "14in liquid retina XDR, 3024 x 1964 resolution, 254 pixels per inch",
      "Processor": "Apple M3 Pro processor 11-core CPU",
      "GPU": "14-core GPU",
      "RAM": "18GB",
      "Ports": "HDMI port, 2 x Thunderbolt 4 (charging, display), 3.5mm headphone jack and a MagSafe 3 port",
      "Camera": "1080p HD camera",
      "Storage": "1Tb SSD",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.3",
      "Weight": "1.55Kg",
      "Dimensions": "(HWD)	1.55 x 31.26 x 22.12 cm",
      "Battery": "Capacity	70Wh lithium-polymer batter, 70Wh power adapter",
      "Operating System": "macOS Sonoma 14.1",
    }
  },
];