import type { TInitialItemGroups, TInitialItemImages, TinitialItems } from '../../types';

const intialItemGroups: TInitialItemGroups = {
  'apple-iphone-16-pro-max': {
    groupName: 'apple-iphone-16-pro-max',
    optionKeys: ['COLOR', 'STORAGE'],
  },
  'apple-iphone-16-pro': {
    groupName: 'apple-iphone-16-pro',
    optionKeys: ['COLOR', 'STORAGE'],
  },
  'apple-iphone-16': {
    groupName: 'apple-iphone-16',
    optionKeys: ['COLOR', 'STORAGE'],
  }
}

const initialItemImages: TInitialItemImages = {
  'apple-iphone-16-pro-max': {
    'black-titanium': [
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-max-black-titanium.jpg',
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-max-black-titanium-2.jpg',
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-max-black-titanium-3.jpg',
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-max-black-titanium-4.jpg'
    ],
    'desert-titanium': [
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-max-desert-titanium.jpg',
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-max-desert-titanium-2.jpg',
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-max-desert-titanium-3.jpg',
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-max-desert-titanium-4.jpg'
    ],
    'natural-titanium': [
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-max-natural-titanium.jpg',
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-max-natural-titanium-2.jpg',
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-max-natural-titanium-3.jpg',
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-max-natural-titanium-4.jpg'
    ],
    'white-titanium': [
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-white-titanium.jpg',
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-white-titanium-2.jpg',
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-white-titanium-3.jpg',
      'items/mobile-phones/apple-iphone-16-pro-max/apple-iphone-16-pro-white-titanium-4.jpg'
    ]
  },
  'apple-iphone-16-pro': {
    'black-titanium': [
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-black-titanium.jpg',
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-black-titanium-2.jpg',
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-black-titanium-3.jpg',
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-black-titanium-4.jpg'
    ],
    'desert-titanium': [
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-desert-titanium.jpg',
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-desert-titanium-2.jpg',
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-desert-titanium-3.jpg',
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-desert-titanium-4.jpg'
    ],
    'natural-titanium': [
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-natural-titanium.jpg',
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-natural-titanium-2.jpg',
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-natural-titanium-3.jpg',
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-natural-titanium-4.jpg'
    ],
    'white-titanium': [
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-white-titanium.jpg',
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-white-titanium-2.jpg',
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-white-titanium-3.jpg',
      'items/mobile-phones/apple-iphone-16-pro/apple-iphone-16-pro-white-titanium-4.jpg'
    ]
  },
  'apple-iphone-16': {
    'ultramarine': [
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-ultramarine.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-ultramarine-2.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-ultramarine-3.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-ultramarine-4.jpg'
    ],
    'teal': [
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-teal.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-teal-2.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-teal-3.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-teal-4.jpg'
    ],
    'pink': [
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-pink.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-pink-2.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-pink-3.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-pink-4.jpg'
    ],
    'white': [
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-white.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-white-2.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-white-3.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-white-4.jpg'
    ],
    'black': [
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-black.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-black-2.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-black-3.jpg',
      'items/mobile-phones/apple-iphone-16/apple-iphone-16-black-4.jpg'
    ],
  },
};

export const initialItems: TinitialItems[] = [
  {
    name: 'Apple Iphone 16 Pro Max 256Gb Black Titanium',
    url: 'apple-iphone-16-pro-max-256gb-black-titanium',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 1199,
    priceDiscount: 1199,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16-pro-max'].groupName,
    groupOptions: {'COLOR': 'Black Titanium', 'STORAGE': '256 Gb'},
    stockQty: 8,
    bestSeller: false,
    forSale: true,
    itemImages: initialItemImages['apple-iphone-16-pro-max']['black-titanium'],
    spec: {
      "SoC":"Apple A18 Pro",
      "CPU":"2x 4.05 GHz, 4x 2.42 GHz, 6 Cores",
      "GPU":"Apple GPU, 6 Cores",
      "RAM":"8 GB, 4266 MHz",
      "Storage": "256 GB",
      "Color": "Black Titanium",
      "Display":"6.9 in, OLED, 1320 x 2868 pixels, 24 bit",
      "Battery":"4685 mAh, Li-Ion",
      "OS":"iOS 18 with Apple Intelligence",
      "Camera":"8000 x 6000 pixels, 3840 x 2160 pixels, 120 fps",
      "Network":"GSM / CDMA / HSPA / EVDO / LTE / 5G",
      "Wi-Fi":"a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "Bluetooth":"45356",
      "SIM card":"eSIM",
      "USB":"3.2, USB Type-C",
      "Positioning":"GPS, A-GPS, GLONASS, BeiDou, Galileo, NavIC, QZSS",
      "Dimensions":"77.6 x 163 x 8.25 mm",
      "Weight":"227 g"
    }
  },
  {
    name: 'Apple Iphone 16 Pro Max 512Gb Desert Titanium',
    url: 'apple-iphone-16-pro-max-512gb-desert-titanium',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 1399,
    priceDiscount: 1399,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16-pro-max'].groupName,
    groupOptions: {'COLOR': 'Desert Titanium', 'STORAGE': '512 Gb'},
    stockQty: 2,
    bestSeller: true,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16-pro-max']['desert-titanium'],
    spec: {
      "SoC":"Apple A18 Pro",
      "CPU":"2x 4.05 GHz, 4x 2.42 GHz, 6 Cores",
      "GPU":"Apple GPU, 6 Cores",
      "RAM":"8 GB, 4266 MHz",
      "Storage": "512 GB",
      "Color": "Desert Titanium",
      "Display":"6.9 in, OLED, 1320 x 2868 pixels, 24 bit",
      "Battery":"4685 mAh, Li-Ion",
      "OS":"iOS 18 with Apple Intelligence",
      "Camera":"8000 x 6000 pixels, 3840 x 2160 pixels, 120 fps",
      "Network":"GSM / CDMA / HSPA / EVDO / LTE / 5G",
      "Wi-Fi":"a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "Bluetooth":"45356",
      "SIM card":"eSIM",
      "USB":"3.2, USB Type-C",
      "Positioning":"GPS, A-GPS, GLONASS, BeiDou, Galileo, NavIC, QZSS",
      "Dimensions":"77.6 x 163 x 8.25 mm",
      "Weight":"227 g"
    }
  },
  {
    name: 'Apple Iphone 16 Pro Max 1Tb Natural Titanium',
    url: 'apple-iphone-16-pro-max-1tb-natural-titanium',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 1699,
    priceDiscount: 1699,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16-pro-max'].groupName,
    groupOptions: {'COLOR': 'Natural Titanium', 'STORAGE': '1 Tb'},
    stockQty: 5,
    bestSeller: true,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16-pro-max']['natural-titanium'],
    spec: {
      "SoC":"Apple A18 Pro",
      "CPU":"2x 4.05 GHz, 4x 2.42 GHz, 6 Cores",
      "GPU":"Apple GPU, 6 Cores",
      "RAM":"8 GB, 4266 MHz",
      "Storage": "1 TB",
      "Color": "Natural Titanium",
      "Display":"6.9 in, OLED, 1320 x 2868 pixels, 24 bit",
      "Battery":"4685 mAh, Li-Ion",
      "OS":"iOS 18 with Apple Intelligence",
      "Camera":"8000 x 6000 pixels, 3840 x 2160 pixels, 120 fps",
      "Network":"GSM / CDMA / HSPA / EVDO / LTE / 5G",
      "Wi-Fi":"a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "Bluetooth":"45356",
      "SIM card":"eSIM",
      "USB":"3.2, USB Type-C",
      "Positioning":"GPS, A-GPS, GLONASS, BeiDou, Galileo, NavIC, QZSS",
      "Dimensions":"77.6 x 163 x 8.25 mm",
      "Weight":"227 g"
    }
  },
  {
    name: 'Apple Iphone 16 Pro Max 1Tb White Titanium',
    url: 'apple-iphone-16-pro-max-1tb-white-titanium',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 1599,
    priceDiscount: 1599,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16-pro-max'].groupName,
    groupOptions: {'COLOR': 'White Titanium', 'STORAGE': '1 Tb'},
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16-pro-max']['white-titanium'],
    spec: {
      "SoC":"Apple A18 Pro",
      "CPU":"2x 4.05 GHz, 4x 2.42 GHz, 6 Cores",
      "GPU":"Apple GPU, 6 Cores",
      "RAM":"8 GB, 4266 MHz",
      "Storage": "1Tb",
      "Color": "White Titanium",
      "Display":"6.9 in, OLED, 1320 x 2868 pixels, 24 bit",
      "Battery":"4685 mAh, Li-Ion",
      "OS":"iOS 18 with Apple Intelligence",
      "Camera":"8000 x 6000 pixels, 3840 x 2160 pixels, 120 fps",
      "Network":"GSM / CDMA / HSPA / EVDO / LTE / 5G",
      "Wi-Fi":"a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "Bluetooth":"45356",
      "SIM card":"eSIM",
      "USB":"3.2, USB Type-C",
      "Positioning":"GPS, A-GPS, GLONASS, BeiDou, Galileo, NavIC, QZSS",
      "Dimensions":"77.6 x 163 x 8.25 mm",
      "Weight":"227 g"
    }
  },
  {
    name: 'Apple Iphone 16 Pro 256Gb Black Titanium',
    url: 'apple-iphone-16-pro-256gb-black-titanium',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 999,
    priceDiscount: 999,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16-pro'].groupName,
    groupOptions: {'COLOR': 'Black Titanium', 'STORAGE': '256 Gb'},
    stockQty: 8,
    bestSeller: false,
    forSale: true,
    itemImages: initialItemImages['apple-iphone-16-pro']['black-titanium'],
    spec: {
      "SoC":"Apple A18 Pro",
      "CPU":"2x 4.05 GHz, 4x 2.42 GHz, 6 Cores",
      "GPU":"Apple GPU, 6 Cores",
      "RAM":"8 GB, 4266 MHz",
      "Storage": "256 GB",
      "Color": "Black Titanium",
      "Display":"6.3 in, OLED, 1206 x 2622 pixels, 24 bit",
      "Battery":"3582 mAh, Li-Ion",
      "OS":"iOS 18 with Apple Intelligence",
      "Camera":"8000 x 6000 pixels, 3840 x 2160 pixels, 120 fps",
      "Network":"GSM / CDMA / HSPA / EVDO / LTE / 5G",
      "Wi-Fi":"a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "Bluetooth":"45356",
      "SIM card":"eSIM",
      "USB":"3.2, USB Type-C",
      "Positioning":"GPS, A-GPS, GLONASS, BeiDou, Galileo, NavIC, QZSS",
      "Dimensions":"71.5 x 149.6 x 8.25 mm",
      "Weight":"199 g"
    }
  },
  {
    name: 'Apple Iphone 16 Pro 512Gb Desert Titanium',
    url: 'apple-iphone-16-pro-512gb-desert-titanium',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 1199,
    priceDiscount: 1199,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16-pro'].groupName,
    groupOptions: {'COLOR': 'Desert Titanium', 'STORAGE': '512 Gb'},
    stockQty: 2,
    bestSeller: true,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16-pro']['desert-titanium'],
    spec: {
      "SoC":"Apple A18 Pro",
      "CPU":"2x 4.05 GHz, 4x 2.42 GHz, 6 Cores",
      "GPU":"Apple GPU, 6 Cores",
      "RAM":"8 GB, 4266 MHz",
      "Storage": "512 GB",
      "Color": "Desert Titanium",
      "Display":"6.3 in, OLED, 1206 x 2622 pixels, 24 bit",
      "Battery":"3582 mAh, Li-Ion",
      "OS":"iOS 18 with Apple Intelligence",
      "Camera":"8000 x 6000 pixels, 3840 x 2160 pixels, 120 fps",
      "Network":"GSM / CDMA / HSPA / EVDO / LTE / 5G",
      "Wi-Fi":"a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "Bluetooth":"45356",
      "SIM card":"eSIM",
      "USB":"3.2, USB Type-C",
      "Positioning":"GPS, A-GPS, GLONASS, BeiDou, Galileo, NavIC, QZSS",
      "Dimensions":"71.5 x 149.6 x 8.25 mm",
      "Weight":"199 g"
    }
  },
  {
    name: 'Apple Iphone 16 Pro 1Tb Natural Titanium',
    url: 'apple-iphone-16-pro-1tb-natural-titanium',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 1499,
    priceDiscount: 1499,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16-pro'].groupName,
    groupOptions: {'COLOR': 'Natural Titanium', 'STORAGE': '1 Tb'},
    stockQty: 5,
    bestSeller: true,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16-pro']['natural-titanium'],
    spec: {
      "SoC":"Apple A18 Pro",
      "CPU":"2x 4.05 GHz, 4x 2.42 GHz, 6 Cores",
      "GPU":"Apple GPU, 6 Cores",
      "RAM":"8 GB, 4266 MHz",
      "Storage": "1 TB",
      "Color": "Natural Titanium",
      "Display":"6.3 in, OLED, 1206 x 2622 pixels, 24 bit",
      "Battery":"3582 mAh, Li-Ion",
      "OS":"iOS 18 with Apple Intelligence",
      "Camera":"8000 x 6000 pixels, 3840 x 2160 pixels, 120 fps",
      "Network":"GSM / CDMA / HSPA / EVDO / LTE / 5G",
      "Wi-Fi":"a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "Bluetooth":"45356",
      "SIM card":"eSIM",
      "USB":"3.2, USB Type-C",
      "Positioning":"GPS, A-GPS, GLONASS, BeiDou, Galileo, NavIC, QZSS",
      "Dimensions":"71.5 x 149.6 x 8.25 mm",
      "Weight":"199 g"
    }
  },
  {
    name: 'Apple Iphone 16 Pro 1Tb White Titanium',
    url: 'apple-iphone-16-pro-1tb-white-titanium',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 1399,
    priceDiscount: 1399,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16-pro'].groupName,
    groupOptions: {'COLOR': 'White Titanium', 'STORAGE': '1 Tb'},
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16-pro']['white-titanium'],
    spec: {
      "SoC":"Apple A18 Pro",
      "CPU":"2x 4.05 GHz, 4x 2.42 GHz, 6 Cores",
      "GPU":"Apple GPU, 6 Cores",
      "RAM":"8 GB, 4266 MHz",
      "Storage": "1Tb",
      "Color": "White Titanium",
      "Display":"6.3 in, OLED, 1206 x 2622 pixels, 24 bit",
      "Battery":"3582 mAh, Li-Ion",
      "OS":"iOS 18 with Apple Intelligence",
      "Camera":"8000 x 6000 pixels, 3840 x 2160 pixels, 120 fps",
      "Network":"GSM / CDMA / HSPA / EVDO / LTE / 5G",
      "Wi-Fi":"a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "Bluetooth":"45356",
      "SIM card":"eSIM",
      "USB":"3.2, USB Type-C",
      "Positioning":"GPS, A-GPS, GLONASS, BeiDou, Galileo, NavIC, QZSS",
      "Dimensions":"71.5 x 149.6 x 8.25 mm",
      "Weight":"199 g"
    }
  },
  {
    name: 'Apple Iphone 16 256Gb White',
    url: 'apple-iphone-16-256gb-white',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 899,
    priceDiscount: 899,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16'].groupName,
    groupOptions: {'COLOR': 'White', 'STORAGE': '256 Gb'},
    stockQty: 5,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16']['white'],
    spec: {
      "SoC": "Apple A18",
      "CPU": "2x 4.04 GHz , 4x 2.2 GHz, Cores: 6",
      "GPU": "Apple GPU, Cores: 5",
      "RAM": "8 GB, 2750 MHz",
      "Storage": "256 Gb",
      "Color": "White",
      "Display": "6.1 in, OLED, 1179 x 2556 pixels, 24 bit",
      "Battery": "3561 mAh, Li-Ion",
      "OS": "iOS 18 with Apple Intelligence",
      "Camera": "8000 x 6000 pixels, 3840 x 2160 pixels, 60 fps",
      "SIM card": "eSIM",
      "Wi-Fi": "a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "USB": "2.0, USB Type-C",
      "Bluetooth": "5.3",
      "Positioning": "GPS, A-GPS, GLONASS, BeiDou, Galileo, QZSS",
      "Dimensions": "71.6 x 147.6 x 7.8 mm",
      "Weight": "170 g",
    }
  },
  {
    name: 'Apple Iphone 16 512Gb Black',
    url: 'apple-iphone-16-512gb-black',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 949,
    priceDiscount: 949,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16'].groupName,
    groupOptions: {'COLOR': 'Black', 'STORAGE': '512 Gb'},
    stockQty: 0,
    bestSeller: false,
    forSale: true,
    itemImages: initialItemImages['apple-iphone-16']['black'],
    spec: {
      "Dimensions": "71.6 x 147.6 x 7.8 mm",
      "Weight": "170 g",
      "SoC": "Apple A18",
      "CPU": "2x 4.04 GHz , 4x 2.2 GHz, Cores: 6",
      "GPU": "Apple GPU, Cores: 5",
      "RAM": "8 GB, 2750 MHz",
      "Storage": "512 Gb",
      "Color": "Black",
      "Display": "6.1 in, OLED, 1179 x 2556 pixels, 24 bit",
      "Battery": "3561 mAh, Li-Ion",
      "OS": "iOS 18 with Apple Intelligence",
      "Camera": "8000 x 6000 pixels, 3840 x 2160 pixels, 60 fps",
      "SIM card": "eSIM",
      "Wi-Fi": "a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "USB": "2.0, USB Type-C",
      "Bluetooth": "5.3",
      "Positioning": "GPS, A-GPS, GLONASS, BeiDou, Galileo, QZSS"
    }
  },
  {
    name: 'Apple Iphone 16 512Gb Teal',
    url: 'apple-iphone-16-512gb-teal',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 949,
    priceDiscount: 949,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16'].groupName,
    groupOptions: {'COLOR': 'Teal', 'STORAGE': '512 Gb'},
    stockQty: 2,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16']['teal'],
    spec: {
      "Dimensions": "71.6 x 147.6 x 7.8 mm",
      "Weight": "170 g",
      "SoC": "Apple A18",
      "CPU": "2x 4.04 GHz , 4x 2.2 GHz, Cores: 6",
      "GPU": "Apple GPU, Cores: 5",
      "RAM": "8 GB, 2750 MHz",
      "Storage": "512 Gb",
      "Color": "Teal",
      "Display": "6.1 in, OLED, 1179 x 2556 pixels, 24 bit",
      "Battery": "3561 mAh, Li-Ion",
      "OS": "iOS 18 with Apple Intelligence",
      "Camera": "8000 x 6000 pixels, 3840 x 2160 pixels, 60 fps",
      "SIM card": "eSIM",
      "Wi-Fi": "a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "USB": "2.0, USB Type-C",
      "Bluetooth": "5.3",
      "Positioning": "GPS, A-GPS, GLONASS, BeiDou, Galileo, QZSS"
    }
  },
  {
    name: 'Apple Iphone 16 512Gb Ultramarine',
    url: 'apple-iphone-16-512gb-ultramarine',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 949,
    priceDiscount: 949,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16'].groupName,
    groupOptions: {'COLOR': 'Ultramarine', 'STORAGE': '512 Gb'},
    stockQty: 2,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16']['ultramarine'],
    spec: {
      "Dimensions": "71.6 x 147.6 x 7.8 mm",
      "Weight": "170 g",
      "SoC": "Apple A18",
      "CPU": "2x 4.04 GHz , 4x 2.2 GHz, Cores: 6",
      "GPU": "Apple GPU, Cores: 5",
      "RAM": "8 GB, 2750 MHz",
      "Storage": "512 Gb",
      "Color": "Ultramarine",
      "Display": "6.1 in, OLED, 1179 x 2556 pixels, 24 bit",
      "Battery": "3561 mAh, Li-Ion",
      "OS": "iOS 18 with Apple Intelligence",
      "Camera": "8000 x 6000 pixels, 3840 x 2160 pixels, 60 fps",
      "SIM card": "eSIM",
      "Wi-Fi": "a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "USB": "2.0, USB Type-C",
      "Bluetooth": "5.3",
      "Positioning": "GPS, A-GPS, GLONASS, BeiDou, Galileo, QZSS"
    }
  },
  {
    name: 'Apple Iphone 16 512Gb Pink',
    url: 'apple-iphone-16-512gb-pink',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 949,
    priceDiscount: 949,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16'].groupName,
    groupOptions: {'COLOR': 'Pink', 'STORAGE': '512 Gb'},
    stockQty: 9,
    bestSeller: false,
    forSale: true,
    itemImages: initialItemImages['apple-iphone-16']['pink'],
    spec: {
      "Dimensions": "71.6 x 147.6 x 7.8 mm",
      "Weight": "170 g",
      "SoC": "Apple A18",
      "CPU": "2x 4.04 GHz , 4x 2.2 GHz, Cores: 6",
      "GPU": "Apple GPU, Cores: 5",
      "RAM": "8 GB, 2750 MHz",
      "Storage": "512 Gb",
      "Color": "Pink",
      "Display": "6.1 in, OLED, 1179 x 2556 pixels, 24 bit",
      "Battery": "3561 mAh, Li-Ion",
      "OS": "iOS 18 with Apple Intelligence",
      "Camera": "8000 x 6000 pixels, 3840 x 2160 pixels, 60 fps",
      "SIM card": "eSIM",
      "Wi-Fi": "a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "USB": "2.0, USB Type-C",
      "Bluetooth": "5.3",
      "Positioning": "GPS, A-GPS, GLONASS, BeiDou, Galileo, QZSS"
    }
  },
  {
    name: 'Apple Iphone 16 512Gb White',
    url: 'apple-iphone-16-512gb-white',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 949,
    priceDiscount: 949,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16'].groupName,
    groupOptions: {'COLOR': 'White', 'STORAGE': '512 Gb'},
    stockQty: 4,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16']['white'],
    spec: {
      "Dimensions": "71.6 x 147.6 x 7.8 mm",
      "Weight": "170 g",
      "SoC": "Apple A18",
      "CPU": "2x 4.04 GHz , 4x 2.2 GHz, Cores: 6",
      "GPU": "Apple GPU, Cores: 5",
      "RAM": "8 GB, 2750 MHz",
      "Storage": "512 Gb",
      "Color": "White",
      "Display": "6.1 in, OLED, 1179 x 2556 pixels, 24 bit",
      "Battery": "3561 mAh, Li-Ion",
      "OS": "iOS 18 with Apple Intelligence",
      "Camera": "8000 x 6000 pixels, 3840 x 2160 pixels, 60 fps",
      "SIM card": "eSIM",
      "Wi-Fi": "a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "USB": "2.0, USB Type-C",
      "Bluetooth": "5.3",
      "Positioning": "GPS, A-GPS, GLONASS, BeiDou, Galileo, QZSS"
    }
  },
  {
    name: 'Apple Iphone 16 128Gb Black',
    url: 'apple-iphone-16-128gb-black',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 799,
    priceDiscount: 799,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16'].groupName,
    groupOptions: {'COLOR': 'Black', 'STORAGE': '128 Gb'},
    stockQty: 0,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16']['black'],
    spec: {
      "Dimensions": "71.6 x 147.6 x 7.8 mm",
      "Weight": "170 g",
      "SoC": "Apple A18",
      "CPU": "2x 4.04 GHz , 4x 2.2 GHz, Cores: 6",
      "GPU": "Apple GPU, Cores: 5",
      "RAM": "8 GB, 2750 MHz",
      "Storage": "128 Gb",
      "Color": "Black",
      "Display": "6.1 in, OLED, 1179 x 2556 pixels, 24 bit",
      "Battery": "3561 mAh, Li-Ion",
      "OS": "iOS 18 with Apple Intelligence",
      "Camera": "8000 x 6000 pixels, 3840 x 2160 pixels, 60 fps",
      "SIM card": "eSIM",
      "Wi-Fi": "a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "USB": "2.0, USB Type-C",
      "Bluetooth": "5.3",
      "Positioning": "GPS, A-GPS, GLONASS, BeiDou, Galileo, QZSS"
    }
  },
  {
    name: 'Apple Iphone 16 128Gb Teal',
    url: 'apple-iphone-16-128gb-teal',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 799,
    priceDiscount: 799,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16'].groupName,
    groupOptions: {'COLOR': 'Teal', 'STORAGE': '128 Gb'},
    stockQty: 1,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16']['teal'],
    spec: {
      "Dimensions": "71.6 x 147.6 x 7.8 mm",
      "Weight": "170 g",
      "SoC": "Apple A18",
      "CPU": "2x 4.04 GHz , 4x 2.2 GHz, Cores: 6",
      "GPU": "Apple GPU, Cores: 5",
      "RAM": "8 GB, 2750 MHz",
      "Storage": "128 Gb",
      "Color": "Teal",
      "Display": "6.1 in, OLED, 1179 x 2556 pixels, 24 bit",
      "Battery": "3561 mAh, Li-Ion",
      "OS": "iOS 18 with Apple Intelligence",
      "Camera": "8000 x 6000 pixels, 3840 x 2160 pixels, 60 fps",
      "SIM card": "eSIM",
      "Wi-Fi": "a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "USB": "2.0, USB Type-C",
      "Bluetooth": "5.3",
      "Positioning": "GPS, A-GPS, GLONASS, BeiDou, Galileo, QZSS"
    }
  },
  {
    name: 'Apple Iphone 16 128Gb Ultramarine',
    url: 'apple-iphone-16-128gb-ultramarine',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 799,
    priceDiscount: 799,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16'].groupName,
    groupOptions: {'COLOR': 'Ultramarine', 'STORAGE': '128 Gb'},
    stockQty: 3,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16']['ultramarine'],
    spec: {
      "SoC": "Apple A18",
      "CPU": "2x 4.04 GHz , 4x 2.2 GHz, Cores: 6",
      "GPU": "Apple GPU, Cores: 5",
      "RAM": "8 GB, 2750 MHz",
      "Storage": "128 Gb",
      "Color": "Ultramarine",
      "Display": "6.1 in, OLED, 1179 x 2556 pixels, 24 bit",
      "Battery": "3561 mAh, Li-Ion",
      "OS": "iOS 18 with Apple Intelligence",
      "Camera": "8000 x 6000 pixels, 3840 x 2160 pixels, 60 fps",
      "SIM card": "eSIM",
      "Wi-Fi": "a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "USB": "2.0, USB Type-C",
      "Bluetooth": "5.3",
      "Positioning": "GPS, A-GPS, GLONASS, BeiDou, Galileo, QZSS",
      "Dimensions": "71.6 x 147.6 x 7.8 mm",
      "Weight": "170 g",
    }
  },
  {
    name: 'Apple Iphone 16 128Gb Pink',
    url: 'apple-iphone-16-128gb-pink',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 799,
    priceDiscount: 799,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16'].groupName,
    groupOptions: {'COLOR': 'Pink', 'STORAGE': '128 Gb'},
    stockQty: 4,
    bestSeller: false,
    forSale: false,
    itemImages: initialItemImages['apple-iphone-16']['pink'],
    spec: {
      "SoC": "Apple A18",
      "CPU": "2x 4.04 GHz , 4x 2.2 GHz, Cores: 6",
      "GPU": "Apple GPU, Cores: 5",
      "RAM": "8 GB, 2750 MHz",
      "Storage": "128 Gb",
      "Color": "Pink",
      "Display": "6.1 in, OLED, 1179 x 2556 pixels, 24 bit",
      "Battery": "3561 mAh, Li-Ion",
      "OS": "iOS 18 with Apple Intelligence",
      "Camera": "8000 x 6000 pixels, 3840 x 2160 pixels, 60 fps",
      "SIM card": "eSIM",
      "Wi-Fi": "a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "USB": "2.0, USB Type-C",
      "Bluetooth": "5.3",
      "Positioning": "GPS, A-GPS, GLONASS, BeiDou, Galileo, QZSS",
      "Dimensions": "71.6 x 147.6 x 7.8 mm",
      "Weight": "170 g",
    }
  },
  {
    name: 'Apple Iphone 16 128Gb White',
    url: 'apple-iphone-16-128gb-white',
    brandId: 2,
    categoryId: 1,
    storeId: 1,
    price: 799,
    priceDiscount: 799,
    ourItem: false,
    groupKey: intialItemGroups['apple-iphone-16'].groupName,
    groupOptions: {'COLOR': 'White', 'STORAGE': '128 Gb'},
    stockQty: 0,
    bestSeller: false,
    forSale: true,
    itemImages: initialItemImages['apple-iphone-16']['white'],
    spec: {
      "SoC": "Apple A18",
      "CPU": "2x 4.04 GHz , 4x 2.2 GHz, Cores: 6",
      "GPU": "Apple GPU, Cores: 5",
      "RAM": "8 GB, 2750 MHz",
      "Storage": "128 Gb",
      "Color": "White",
      "Display": "6.1 in, OLED, 1179 x 2556 pixels, 24 bit",
      "Battery": "3561 mAh, Li-Ion",
      "OS": "iOS 18 with Apple Intelligence",
      "Camera": "8000 x 6000 pixels, 3840 x 2160 pixels, 60 fps",
      "SIM card": "eSIM",
      "Wi-Fi": "a, b, g, n, n 5GHz, ac, Wi-Fi 7 (be), Wi-Fi Hotspot",
      "USB": "2.0, USB Type-C",
      "Bluetooth": "5.3",
      "Positioning": "GPS, A-GPS, GLONASS, BeiDou, Galileo, QZSS",
      "Dimensions": "71.6 x 147.6 x 7.8 mm",
      "Weight": "170 g",
    }
  },
];
