import type { TInitialItemGroups, TInitialItemImages, TinitialItems } from '../../types';

const intialItemGroups: TInitialItemGroups = {
  'philips-42m2n8900': {
    groupName: 'philips-42m2n8900',
    optionKeys: [],
  },
  'xiaomi-tv-s-mini-led-2025': {
    groupName: 'xiaomi-tv-s-mini-led-2025',
    optionKeys: ["SIZE"],
  },
  'samsung-qled-neo': {
    groupName: 'samsung-qled-neo',
    optionKeys: ["SIZE"],
  },
}



const initialItemImages: TInitialItemImages = {
  'philips-42m2n8900': [
    'items/tv/philips-42m2n8900/philips-42m2n8900.jpg',
    'items/tv/philips-42m2n8900/philips-42m2n8900-2.jpg',
    'items/tv/philips-42m2n8900/philips-42m2n8900-3.jpg',
    'items/tv/philips-42m2n8900/philips-42m2n8900-4.jpg',
  ],
  'xiaomi-tv-s-mini-led-2025': [
    'items/tv/xiaomi-tv-s-mini-led-2025/xiaomi-tv-s-mini-led-2025.jpg',
    'items/tv/xiaomi-tv-s-mini-led-2025/xiaomi-tv-s-mini-led-2025-2.jpg',
    'items/tv/xiaomi-tv-s-mini-led-2025/xiaomi-tv-s-mini-led-2025-3.jpg',
    'items/tv/xiaomi-tv-s-mini-led-2025/xiaomi-tv-s-mini-led-2025-4.jpg',
    'items/tv/xiaomi-tv-s-mini-led-2025/xiaomi-tv-s-mini-led-2025-5.jpg',
    'items/tv/xiaomi-tv-s-mini-led-2025/xiaomi-tv-s-mini-led-2025-6.jpg',
  ],
  'samsung-qled-neo': [
    'items/tv/samsung-qled-neo/samsung-qled-neo.jpg',
    'items/tv/samsung-qled-neo/samsung-qled-neo-2.jpg',
    'items/tv/samsung-qled-neo/samsung-qled-neo-3.jpg',
    'items/tv/samsung-qled-neo/samsung-qled-neo-4.jpg',
    'items/tv/samsung-qled-neo/samsung-qled-neo-5.jpg',
    'items/tv/samsung-qled-neo/samsung-qled-neo-6.jpg',
  ],
};

export const initialItems: TinitialItems[] = [
  {
    name: 'Philips OLED TV 42" 42M2N8900',
    url: 'philips-oled-tv-42-42m2n8900',
    brandId: 8,
    categoryId: 7,
    storeId: 1,
    price: 2499,
    priceDiscount: 2499,
    ourItem: true,
    groupKey: intialItemGroups['philips-42m2n8900'].groupName,
    groupOptions: {},
    stockQty: 10,
    bestSeller: true,
    forSale: false,
    itemImages: Array.isArray(initialItemImages['philips-42m2n8900']) && initialItemImages['philips-42m2n8900'],
    spec: {
      "Brand":"PHILIPS",
      "Screen size":"42 Inches",
      "Resolution":"4K UHD 2160p",
      "Aspect ratio":"16:9",
      "Screen surface description":"Glossy",
      "Image contrast ratio":"1000000:1",
      "Response time":"0.1 Milliseconds",
      "Refresh rate":"138 Hz",
      "Power consumption":"90 Watts",
      "Display resolution maximum	":"3840 x 2160 Pixels",
    }
  },
  {
    name: 'Xiaomi TV S Mini LED 65" 2025',
    url: 'xiaomi-tv-s-mini-led-65-2025',
    brandId: 13,
    categoryId: 7,
    storeId: 1,
    price: 2299,
    priceDiscount: 2299,
    ourItem: true,
    groupKey: intialItemGroups['xiaomi-tv-s-mini-led-2025'].groupName,
    groupOptions: {'SIZE': '65"'},
    stockQty: 10,
    bestSeller: false,
    forSale: false,
    itemImages: Array.isArray(initialItemImages['xiaomi-tv-s-mini-led-2025']) && initialItemImages['xiaomi-tv-s-mini-led-2025'],
    spec: {
      "Brand":"Xiaomi",
      "Screen size":"65 Inches",
      "Display technology":"4KUHD, LED",
      "Resolution":"4K",
      "Refresh rate":"144Hz",
      "Special features":"AI-Driven Image Enhancement, QD-MiniLED Display",
      "Included components":"TV, remote control, cable",
      "Connectivity technology":"Bluetooth",
    },
  },
  {
    name: 'Xiaomi TV S Mini LED 75" 2025',
    url: 'xiaomi-tv-s-mini-led-75-2025',
    brandId: 13,
    categoryId: 7,
    storeId: 1,
    price: 2999,
    priceDiscount: 2899,
    ourItem: true,
    groupKey: intialItemGroups['xiaomi-tv-s-mini-led-2025'].groupName,
    groupOptions: {'SIZE': '75"'},
    stockQty: 10,
    bestSeller: false,
    forSale: true,
    itemImages: Array.isArray(initialItemImages['xiaomi-tv-s-mini-led-2025']) && initialItemImages['xiaomi-tv-s-mini-led-2025'],
    spec: {
      "Brand":"Xiaomi",
      "Screen size":"75 Inches",
      "Display technology":"4KUHD, LED",
      "Resolution":"4K",
      "Refresh rate":"144Hz",
      "Special features":"AI-Driven Image Enhancement, QD-MiniLED Display",
      "Included components":"TV, remote control, cable",
      "Connectivity technology":"Bluetooth",
    },
  },
  {
    name: 'Xiaomi TV S Mini LED 55" 2025',
    url: 'xiaomi-tv-s-mini-led-55-2025',
    brandId: 13,
    categoryId: 7,
    storeId: 1,
    price: 1499,
    priceDiscount: 1499,
    ourItem: true,
    groupKey: intialItemGroups['xiaomi-tv-s-mini-led-2025'].groupName,
    groupOptions: {'SIZE': '55"'},
    stockQty: 10,
    bestSeller: true,
    forSale: false,
    itemImages: Array.isArray(initialItemImages['xiaomi-tv-s-mini-led-2025']) && initialItemImages['xiaomi-tv-s-mini-led-2025'],
    spec: {
      "Brand":"Xiaomi",
      "Screen size":"55 Inches",
      "Display technology":"4KUHD, LED",
      "Resolution":"4K",
      "Refresh rate":"144Hz",
      "Special features":"AI-Driven Image Enhancement, QD-MiniLED Display",
      "Included components":"TV, remote control, cable",
      "Connectivity technology":"Bluetooth",
    },
  },
  {
    name: 'Samsung Neo QLED 4K QN90C 43"',
    url: 'samsung-neo-qled-4k-qn90c-43',
    brandId: 9,
    categoryId: 7,
    storeId: 1,
    price: 1199,
    priceDiscount: 1199,
    ourItem: true,
    groupKey: intialItemGroups['samsung-qled-neo'].groupName,
    groupOptions: {'SIZE': '43"'},
    stockQty: 10,
    bestSeller: false,
    forSale: false,
    itemImages: Array.isArray(initialItemImages['samsung-qled-neo']) && initialItemImages['samsung-qled-neo'],
    spec: {
      "Brand":"SAMSUNG",
      "Screen Size":"43 Inches",
      "Display Technology":"QLED",
      "Resolution":"4K",
      "Refresh Rate":"120 Hz",
      "Special Feature":"100% Color Volume; Motion Xcelerator Turbo+; Filmmaker Mode; Works with Google Assistant and Alexa, Quantum Matrix with Mini LEDs; Neo Quantum HDR+; Neural Quantum Processor 4K; Anti-Glare with Ultra Viewing Angle100% Color Volume; Motion Xcelerator Turbo+; Filmmaker Mode; Works with Google Assistant and Alexa, Quantum Matrix with Mini LEDs; Neo Quantum HDR+; Neural Quantum Processor 4K; Anti-Glare with Ultra Viewing Angle",
      "Included Components":"User Manual, E-Manual,Power Cable",
      "Connectivity Technology":"Bluetooth, Wi-Fi, USB, Ethernet, HDMI",
      "Aspect Ratio":"16:9",
    }
  },
  {
    name: 'Samsung Neo QLED 4K QN90C 55"',
    url: 'samsung-neo-qled-4k-qn90c-55',
    brandId: 9,
    categoryId: 7,
    storeId: 1,
    price: 1999,
    priceDiscount: 1999,
    ourItem: true,
    groupKey: intialItemGroups['samsung-qled-neo'].groupName,
    groupOptions: {'SIZE': '55"'},
    stockQty: 10,
    bestSeller: false,
    forSale: false,
    itemImages: Array.isArray(initialItemImages['samsung-qled-neo']) && initialItemImages['samsung-qled-neo'],
    spec: {
      "Brand":"SAMSUNG",
      "Screen Size":"55 Inches",
      "Display Technology":"QLED",
      "Resolution":"4K",
      "Refresh Rate":"120 Hz",
      "Special Feature":"100% Color Volume; Motion Xcelerator Turbo+; Filmmaker Mode; Works with Google Assistant and Alexa, Quantum Matrix with Mini LEDs; Neo Quantum HDR+; Neural Quantum Processor 4K; Anti-Glare with Ultra Viewing Angle100% Color Volume; Motion Xcelerator Turbo+; Filmmaker Mode; Works with Google Assistant and Alexa, Quantum Matrix with Mini LEDs; Neo Quantum HDR+; Neural Quantum Processor 4K; Anti-Glare with Ultra Viewing Angle",
      "Included Components":"User Manual, E-Manual,Power Cable",
      "Connectivity Technology":"Bluetooth, Wi-Fi, USB, Ethernet, HDMI",
      "Aspect Ratio":"16:9",
    }
  },
  {
    name: 'Samsung Neo QLED 4K QN90C 65"',
    url: 'samsung-neo-qled-4k-qn90c-65',
    brandId: 9,
    categoryId: 7,
    storeId: 1,
    price: 2199,
    priceDiscount: 2199,
    ourItem: true,
    groupKey: intialItemGroups['samsung-qled-neo'].groupName,
    groupOptions: {'SIZE': '65"'},
    stockQty: 0,
    bestSeller: true,
    forSale: false,
    itemImages: Array.isArray(initialItemImages['samsung-qled-neo']) && initialItemImages['samsung-qled-neo'],
    spec: {
      "Brand":"SAMSUNG",
      "Screen Size":"65 Inches",
      "Display Technology":"QLED",
      "Resolution":"4K",
      "Refresh Rate":"120 Hz",
      "Special Feature":"100% Color Volume; Motion Xcelerator Turbo+; Filmmaker Mode; Works with Google Assistant and Alexa, Quantum Matrix with Mini LEDs; Neo Quantum HDR+; Neural Quantum Processor 4K; Anti-Glare with Ultra Viewing Angle100% Color Volume; Motion Xcelerator Turbo+; Filmmaker Mode; Works with Google Assistant and Alexa, Quantum Matrix with Mini LEDs; Neo Quantum HDR+; Neural Quantum Processor 4K; Anti-Glare with Ultra Viewing Angle",
      "Included Components":"User Manual, E-Manual,Power Cable",
      "Connectivity Technology":"Bluetooth, Wi-Fi, USB, Ethernet, HDMI",
      "Aspect Ratio":"16:9",
    }
  },
];
